/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ManageBookingRouteImport } from './routes/manage-booking'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingIndexRouteImport } from './routes/booking.index'
import { Route as RoomsIdRouteImport } from './routes/rooms.$id'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as BookingRoomsRouteImport } from './routes/booking.rooms'
import { Route as BookingPaymentRouteImport } from './routes/booking.payment'
import { Route as BookingGuestRouteImport } from './routes/booking.guest'
import { Route as BookingExtrasRouteImport } from './routes/booking.extras'
import { Route as BookingDatesRouteImport } from './routes/booking.dates'
import { Route as BookingConfirmationRefRouteImport } from './routes/booking.confirmation.$ref'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageBookingRoute = ManageBookingRouteImport.update({
  id: '/manage-booking',
  path: '/manage-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIndexRoute = BookingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingRoute,
} as any)
const RoomsIdRoute = RoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/experiences/$slug',
  path: '/experiences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoomsRoute = BookingRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => BookingRoute,
} as any)
const BookingPaymentRoute = BookingPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => BookingRoute,
} as any)
const BookingGuestRoute = BookingGuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => BookingRoute,
} as any)
const BookingExtrasRoute = BookingExtrasRouteImport.update({
  id: '/extras',
  path: '/extras',
  getParentRoute: () => BookingRoute,
} as any)
const BookingDatesRoute = BookingDatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => BookingRoute,
} as any)
const BookingConfirmationRefRoute = BookingConfirmationRefRouteImport.update({
  id: '/confirmation/$ref',
  path: '/confirmation/$ref',
  getParentRoute: () => BookingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRouteWithChildren
  '/manage-booking': typeof ManageBookingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/booking/dates': typeof BookingDatesRoute
  '/booking/extras': typeof BookingExtrasRoute
  '/booking/guest': typeof BookingGuestRoute
  '/booking/payment': typeof BookingPaymentRoute
  '/booking/rooms': typeof BookingRoomsRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/booking/': typeof BookingIndexRoute
  '/booking/confirmation/$ref': typeof BookingConfirmationRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage-booking': typeof ManageBookingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/booking/dates': typeof BookingDatesRoute
  '/booking/extras': typeof BookingExtrasRoute
  '/booking/guest': typeof BookingGuestRoute
  '/booking/payment': typeof BookingPaymentRoute
  '/booking/rooms': typeof BookingRoomsRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/booking': typeof BookingIndexRoute
  '/booking/confirmation/$ref': typeof BookingConfirmationRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRouteWithChildren
  '/manage-booking': typeof ManageBookingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/booking/dates': typeof BookingDatesRoute
  '/booking/extras': typeof BookingExtrasRoute
  '/booking/guest': typeof BookingGuestRoute
  '/booking/payment': typeof BookingPaymentRoute
  '/booking/rooms': typeof BookingRoomsRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/booking/': typeof BookingIndexRoute
  '/booking/confirmation/$ref': typeof BookingConfirmationRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/manage-booking'
    | '/sitemap.xml'
    | '/booking/dates'
    | '/booking/extras'
    | '/booking/guest'
    | '/booking/payment'
    | '/booking/rooms'
    | '/experiences/$slug'
    | '/rooms/$id'
    | '/booking/'
    | '/booking/confirmation/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manage-booking'
    | '/sitemap.xml'
    | '/booking/dates'
    | '/booking/extras'
    | '/booking/guest'
    | '/booking/payment'
    | '/booking/rooms'
    | '/experiences/$slug'
    | '/rooms/$id'
    | '/booking'
    | '/booking/confirmation/$ref'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/manage-booking'
    | '/sitemap.xml'
    | '/booking/dates'
    | '/booking/extras'
    | '/booking/guest'
    | '/booking/payment'
    | '/booking/rooms'
    | '/experiences/$slug'
    | '/rooms/$id'
    | '/booking/'
    | '/booking/confirmation/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRouteWithChildren
  ManageBookingRoute: typeof ManageBookingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
  RoomsIdRoute: typeof RoomsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-booking': {
      id: '/manage-booking'
      path: '/manage-booking'
      fullPath: '/manage-booking'
      preLoaderRoute: typeof ManageBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/': {
      id: '/booking/'
      path: '/'
      fullPath: '/booking/'
      preLoaderRoute: typeof BookingIndexRouteImport
      parentRoute: typeof BookingRoute
    }
    '/rooms/$id': {
      id: '/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof RoomsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/experiences/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/rooms': {
      id: '/booking/rooms'
      path: '/rooms'
      fullPath: '/booking/rooms'
      preLoaderRoute: typeof BookingRoomsRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/payment': {
      id: '/booking/payment'
      path: '/payment'
      fullPath: '/booking/payment'
      preLoaderRoute: typeof BookingPaymentRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/guest': {
      id: '/booking/guest'
      path: '/guest'
      fullPath: '/booking/guest'
      preLoaderRoute: typeof BookingGuestRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/extras': {
      id: '/booking/extras'
      path: '/extras'
      fullPath: '/booking/extras'
      preLoaderRoute: typeof BookingExtrasRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/dates': {
      id: '/booking/dates'
      path: '/dates'
      fullPath: '/booking/dates'
      preLoaderRoute: typeof BookingDatesRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/confirmation/$ref': {
      id: '/booking/confirmation/$ref'
      path: '/confirmation/$ref'
      fullPath: '/booking/confirmation/$ref'
      preLoaderRoute: typeof BookingConfirmationRefRouteImport
      parentRoute: typeof BookingRoute
    }
  }
}

interface BookingRouteChildren {
  BookingDatesRoute: typeof BookingDatesRoute
  BookingExtrasRoute: typeof BookingExtrasRoute
  BookingGuestRoute: typeof BookingGuestRoute
  BookingPaymentRoute: typeof BookingPaymentRoute
  BookingRoomsRoute: typeof BookingRoomsRoute
  BookingIndexRoute: typeof BookingIndexRoute
  BookingConfirmationRefRoute: typeof BookingConfirmationRefRoute
}

const BookingRouteChildren: BookingRouteChildren = {
  BookingDatesRoute: BookingDatesRoute,
  BookingExtrasRoute: BookingExtrasRoute,
  BookingGuestRoute: BookingGuestRoute,
  BookingPaymentRoute: BookingPaymentRoute,
  BookingRoomsRoute: BookingRoomsRoute,
  BookingIndexRoute: BookingIndexRoute,
  BookingConfirmationRefRoute: BookingConfirmationRefRoute,
}

const BookingRouteWithChildren =
  BookingRoute._addFileChildren(BookingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRouteWithChildren,
  ManageBookingRoute: ManageBookingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ExperiencesSlugRoute: ExperiencesSlugRoute,
  RoomsIdRoute: RoomsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
